- name: install http service 
  hosts: web
  gather_facts: yes
  vars:
    package_name: httpd
  tasks:
  - name: install http web server
    yum:
      name: '{{package_name}}'
      state: present  ###here we can use 'state = absent' , and absent mean uninstall the httpd service##
  - name: start http service 
    service:
      name: httpd
      state: started
      enabled: true
  - name: allow http service on firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
  - name: copy content for http server
    copy:
      src: /mnt/index.html #if you want to copy file from mapped directory
#     content: "welcome to hello world" ##(if you want to input any content)
      dest: /var/www/html/
